{{- if .Values.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redstone-mud.fullname" . }}-env
  labels:
    {{- include "redstone-mud.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}