{{- if .Values.config.metrics.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "multichain-aggregator.fullname" . }}
  labels:
    {{- include "multichain-aggregator.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: "15s"
    scrapeTimeout: "5s"
    path: /metrics
    targetPort: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "multichain-aggregator.fullname" . }}
{{- end }}