apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pganalyzer.fullname" . }}-env
  labels:
    {{- include "pganalyzer.labels" . | nindent 4 }}
type: Opaque
data:
  PGA_API_KEY: {{ .Values.api.key | b64enc }}
  PGA_API_SYSTEM_ID: {{ .Values.api.systemId | b64enc }}
  DB_HOST: {{ .Values.db.host | b64enc }}
  DB_NAME: {{ .Values.db.name | b64enc }}
  DB_USERNAME: {{ .Values.db.username | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
{{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---