apiVersion: v1
kind: Secret
metadata:
  name: admin-ts-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_DATABASE_URL: {{ .Values.adminRs.config.databaseUrl | b64enc }}
  CONTRACTS_INFO_DATABASE_URL: {{ .Values.contractsInfo.config.databaseUrl | b64enc }}
  CONTRACTS_INFO_API_KEY: {{ .Values.contractsInfo.config.apiKeys.adminjs | b64enc }}
{{- range .Values.adminTs.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
---