apiVersion: v1
kind: Secret
metadata:
  name: admin-rs-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_RS__DATABASE__URL: {{ .Values.adminRs.config.databaseUrl | b64enc }}
{{- range .Values.adminRs.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- range .Values.config.network }}
  ADMIN_RS__CHAINS_CONFIG__NETWORKS__{{ .id }}__API_KEY: {{ .apiKey | b64enc }}
{{- end }}
---