apiVersion: v1
kind: Secret
metadata:
  name: metadata-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.metadata.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
---