{{- if .Values.tokenInfoExtractor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: token-info-extractor-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
  TOKEN_INFO_EXTRACTOR__CONTRACTS_INFO__API_KEY: {{ .Values.contractsInfo.config.apiKeys.extractor1 | b64enc }}
  TOKEN_INFO_EXTRACTOR__DATABASE__URL: {{ .Values.tokenInfoExtractor.config.databaseUrl | b64enc }}
{{- range .Values.tokenInfoExtractor.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
---