apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracker.fullname" . }}-env
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
type: Opaque
data:
  CLICKHOUSE_PASSWORD: {{ .Values.config.clickhouse.password | b64enc }}