{{- if not .Values.config.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph-node.fullname" . }}-db
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.config.postgres.user | b64enc | quote }}
  password: {{ .Values.config.postgres.pass | b64enc | quote }}
{{- end }}