apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-ens.fullname" . }}-config
  labels:
    {{- include "blockscout-ens.labels" . | nindent 4 }}
data:
  config.json: {{ toYaml .Values.bens.config.file | indent 2 }}