apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-ens.fullname" . }}-bens-svc
  labels:
    app: {{ .Release.Name }}-bens-svc
    {{- include "blockscout-ens.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bens.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 6060
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Release.Name }}-bens
