{{- if .Values.bens.ingress.enabled }}
{{- $fullName := include "blockscout-ens.fullname" . -}}
{{- $svcPort := "80" -}}
{{- if and .Values.bens.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-bens-ingress
  labels:
    {{- include "blockscout-ens.labels" . | nindent 4 }}
  {{- with .Values.bens.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.bens.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.bens.ingress.className }}
  {{- end }}
  {{- if .Values.bens.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.bens.ingress.hostname | quote }}
      secretName: {{ $fullName }}-bens-tls
  {{- end }}
  rules:
    - host: {{ .Values.bens.ingress.hostname | quote }}
      http:
        paths:
          {{- range .Values.bens.ingress.paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-bens-svc
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-bens-svc
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
{{- end }}
