apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-ens.fullname" . }}-bens-env
  labels:
    {{- include "blockscout-ens.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.bens.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
