{{- if .Values.ethBytecodeDb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-contract-verification.fullname" . }}-eth-bytecode-db
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ethBytecodeDb.service.type }}
  ports:
    - port: {{ .Values.ethBytecodeDb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app: {{ include "smart-contract-verification.fullname" . }}-eth-bytecode-db
    {{- include "smart-contract-verification.selectorLabels" . | nindent 4 }}
{{- end }}