{{- if .Values.ethBytecodeDb.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-contract-verification.fullname" . }}-eth-bytecode-db-env
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.ethBytecodeDb.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}