{{- if and .Values.metrics.enabled .Values.metrics.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "smart-contract-verification.fullname" . }}-sig-provider
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
spec:
  endpoints:
  - scrapeTimeout: 30s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app: {{ include "smart-contract-verification.fullname" . }}-sig-provider
{{- end }}