{{- if .Values.smartContractVerifier.ingress.enabled -}}
{{- $fullName := include "smart-contract-verification.fullname" . -}}
{{- $svcPort := .Values.smartContractVerifier.service.port -}}
{{- if and .Values.smartContractVerifier.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.smartContractVerifier.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.smartContractVerifier.ingress.annotations "kubernetes.io/ingress.class" .Values.smartContractVerifier.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-smart-contract-verifier
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
  {{- with .Values.smartContractVerifier.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.smartContractVerifier.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.smartContractVerifier.ingress.className }}
  {{- end }}
  {{- if .Values.smartContractVerifier.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.smartContractVerifier.ingress.hostname | quote }}
      secretName: {{ $fullName }}-smart-contract-verifier-ingress-tls
  {{- end }}
  rules:
    - host: {{ .Values.smartContractVerifier.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-smart-contract-verifier
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-smart-contract-verifier
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
---
{{- if .Values.smartContractVerifier.grpc.ingress.enabled -}}
{{- $fullName := include "smart-contract-verification.fullname" . -}}
{{- $svcPort := .Values.smartContractVerifier.grpc.port -}}
{{- if and .Values.smartContractVerifier.grpc.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.smartContractVerifier.grpc.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.smartContractVerifier.grpc.ingress.annotations "kubernetes.io/ingress.class" .Values.smartContractVerifier.grpc.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-smart-contract-verifier-grpc
  labels:
    {{- include "smart-contract-verification.labels" . | nindent 4 }}
  {{- with .Values.smartContractVerifier.grpc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.smartContractVerifier.grpc.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.smartContractVerifier.grpc.ingress.className }}
  {{- end }}
  {{- if .Values.smartContractVerifier.grpc.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.smartContractVerifier.grpc.ingress.hostname | quote }}
      secretName: {{ $fullName }}-grpc-smart-contract-verifier-ingress-tls
  {{- end }}
  rules:
    - host: {{ .Values.smartContractVerifier.grpc.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-smart-contract-verifier
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-smart-contract-verifier
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}