{{- if .Values.backend.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-points.fullname" . }}-backend-env
  labels:
    {{- include "blockscout-points.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.backend.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-points.fullname" . }}-backend-config
  labels:
    {{- include "blockscout-points.labels" . | nindent 4 }}
type: Opaque
data:
  adminApiKey: {{ .Values.backend.config.auth.adminApiKey | b64enc | quote }}
  jwtSecret: {{ .Values.backend.config.auth.jwtSecret | b64enc | quote }}
{{- if not .Values.backend.config.database.existingSecret }}
  username: {{ .Values.backend.config.database.user | b64enc | quote }}
  password: {{ .Values.backend.config.database.pass | b64enc | quote }}
{{- end }}