{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "eth-rpc-exporter.fullname" . }}
  labels:
    {{- include "eth-rpc-exporter.labels" . | nindent 4 }}
spec:
{{- with .Values.prometheusRule.rules }}
  groups:
    - name: eth-rpc-monitoring
      rules:
{{ toYaml .| indent 8 }}
{{- end }}
{{- end }}