apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eth-rpc-exporter.fullname" . }}-config
  labels:
    {{- include "eth-rpc-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: {{ include "eth-rpc-exporter.config" . | b64enc }}
---