apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eth-tx-summary-api.fullname" . }}-env
  labels:
    {{- include "eth-tx-summary-api.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---