{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "autoscout.fullname" . }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
spec:
{{- with .Values.prometheusRule.rules }}
  groups:
    - name: autoscout-monitoring
      rules:
{{ toYaml .| indent 8 }}
{{- end }}
{{- end }}

