apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-generator.fullname" . }}-env
  labels:
    {{- include "image-generator.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---