{{- if and .Values.blockscout.enabled .Values.blockscout.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-env
  labels:
    {{- include "blockscout-stack.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.blockscout.nftStorage.enabled }}
  RELEASE_COOKIE: {{ .Values.blockscout.nftStorage.cookie | b64enc }}
  NFT_MEDIA_HANDLER_AWS_PUBLIC_BUCKET_URL: {{ .Values.blockscout.nftStorage.bucketUrl | b64enc }}
{{- end }}
{{- range $key, $value := .Values.blockscout.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- if .Values.blockscout.nftStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-resizer
  labels:
    {{- include "blockscout-stack.labels" . | nindent 4 }}
type: Opaque
data:
  RELEASE_COOKIE: {{ .Values.blockscout.nftStorage.cookie | b64enc }}
  NFT_MEDIA_HANDLER_AWS_BUCKET_HOST: {{ .Values.blockscout.nftStorage.bucketHost | b64enc }}
  NFT_MEDIA_HANDLER_AWS_ACCESS_KEY_ID: {{ .Values.blockscout.nftStorage.accessKey | b64enc }}
  NFT_MEDIA_HANDLER_AWS_SECRET_ACCESS_KEY: {{ .Values.blockscout.nftStorage.secretKey | b64enc }}
  NFT_MEDIA_HANDLER_AWS_BUCKET_NAME: {{ .Values.blockscout.nftStorage.bucketName | b64enc }}
  NFT_MEDIA_HANDLER_AWS_PUBLIC_BUCKET_URL: {{ .Values.blockscout.nftStorage.bucketUrl | b64enc }}
{{- end }}
{{- end }}