{{- if and .Values.blockscout.ingress.enabled .Values.config.prometheus.blackbox.enabled }}
{{- $url := printf "https://%s%s" .Values.blockscout.ingress.hostname .Values.config.prometheus.blackbox.path }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-blockscout-bb
  labels:
    {{- include "blockscout-stack.labels" . | nindent 4 }}
spec:
  endpoints:
  - scrapeTimeout: {{ .Values.config.prometheus.blackbox.scrapeTimeout }}
    port: http
    path: "/probe"
    interval: {{ .Values.config.prometheus.blackbox.interval }}
    params:
      module:
      - {{ .Values.config.prometheus.blackbox.module }}
      target:
      - {{ $url }}
    metricRelabelings:
      - targetLabel: instance
        replacement: {{ $url }}
      - targetLabel: target
        replacement: {{ include "blockscout-stack.fullname" . }}
        {{- range $key, $value := .Values.config.prometheus.blackbox.extraLabels }}
      - targetLabel: {{ $key }}
        replacement: {{ $value }}
        {{- end }}
  namespaceSelector:
    any: true
  selector:
    {{- toYaml .Values.config.prometheus.blackbox.selector | nindent 4 }}
{{- end }}