{{- if .Values.stats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout-stack.fullname" . }}-stats-svc
  labels:
    app: {{ include "blockscout-stack.fullname" . }}-stats-svc
    {{- include "blockscout-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stats.service.type }}
  ports:
    - port: {{ .Values.stats.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.stats.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ include "blockscout-stack.fullname" . }}-stats
{{- end }}