{{- if .Values.consensus.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rpc-node.fullname" . }}-consensus
  labels:
    app: {{ .Release.Name }}-consensus
    {{- include "rpc-node.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "rpc-node.fullname" . }}-consensus
  selector:
    matchLabels:
      app: {{ .Release.Name }}-consensus
      {{- include "rpc-node.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  {{- if .Values.consensus.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: consensus-data
    spec:
      accessModes:
      {{- range .Values.consensus.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.consensus.persistence.size | quote }}
    {{- if .Values.consensus.persistence.storageClass }}
    {{- if (eq "-" .Values.consensus.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.consensus.persistence.storageClass }}"
    {{- end }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.consensus.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-consensus
        {{- include "rpc-node.labels" . | nindent 8 }}
        {{- with .Values.consensus.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rpc-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.consensus.podSecurityContext | nindent 8 }}
      containers:
        - name: consensus
          securityContext:
            {{- toYaml .Values.consensus.securityContext | nindent 12 }}
          image: "{{ .Values.consensus.image.repository }}:{{ .Values.consensus.image.tag }}"
          imagePullPolicy: {{ .Values.consensus.image.pullPolicy }}
          {{- with .Values.consensus.command }}
          command:  {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (concat .Values.consensus.args .Values.consensus.extraArgs) }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.consensus.env }}
          env:
          {{- range $key, $value := .Values.consensus.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.consensus.envFromSecret }}
          envFrom:
          - secretRef:
              name: {{ include "rpc-node.fullname" . }}-consensus-env
          {{- range .Values.consensus.envFrom }}
          - {{ toYaml . | nindent 12 | trim }}
          {{- end }}
          {{- end }}
          ports:
            {{- range .Values.consensus.service.cluster.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
            {{- range .Values.consensus.service.node.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.consensus.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.consensus.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.consensus.resources | nindent 12 }}
          {{- if or .Values.consensus.persistence.enabled .Values.consensus.volumeMounts .Values.config.jwtsecret.enabled .Values.consensus.configFiles.enabled }}
          volumeMounts:
            {{- if .Values.consensus.persistence.enabled }}
            - name:  consensus-data
              mountPath: {{ .Values.consensus.persistence.mountPath }}
            {{- end }}
            {{- if .Values.config.jwtsecret.enabled }}
            - name: jwtsecret
              mountPath: /app/config/jwtsecret
              subPath: jwtsecret
            {{- end }}
            {{- if .Values.consensus.configFiles.enabled }}
            - name: configfiles
              mountPath: {{ .Values.consensus.configFiles.mountPath }}
            {{- end }}
          {{- with .Values.consensus.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.consensus.volumes .Values.config.jwtsecret.enabled .Values.consensus.configFiles.enabled }}
      volumes:
      {{- if .Values.config.jwtsecret.enabled }}
        - name: jwtsecret
          secret:
            secretName: {{ include "rpc-node.fullname" . }}-jwtsecret
      {{- end }}
      {{- if .Values.consensus.configFiles.enabled }}
        - name: configfiles
          configMap:
            name: {{ include "rpc-node.fullname" . }}-consensus-files
        {{- end }}
      {{- with .Values.consensus.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: 300
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}