{{- if .Values.consensus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpc-node.fullname" . }}-consensus-cluster
  labels:
    {{- include "rpc-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.consensus.service.cluster.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-consensus
    {{- include "rpc-node.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpc-node.fullname" . }}-consensus-node
  labels:
    {{- include "rpc-node.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    {{- range .Values.consensus.service.node.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      nodePort: {{ .port }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-consensus
    {{- include "rpc-node.selectorLabels" . | nindent 4 }}
{{- end }}