{{- if .Values.execution.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rpc-node.fullname" . }}-execution-env
  labels:
    {{- include "rpc-node.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.execution.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}